server.port=8000
# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.netflix.eureka.discovery.enabled=true

# Disable auto route (optional)
spring.cloud.gateway.discovery.locator.enabled=false

# Product Service Route
spring.cloud.gateway.routes[0].id=productservice
spring.cloud.gateway.routes[0].uri=lb://PRODUCTSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**


# Order Service Route
spring.cloud.gateway.routes[1].id=Orderservice
spring.cloud.gateway.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
